name: crypto_please_challenge
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

  # Net
  dio: ^4.0.4
  pretty_dio_logger: ^1.1.1
  retrofit: '>=3.0.0 <4.0.0'

  # Architecture
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  flutter_bloc: ^8.0.0
  bloc_test: ^9.0.2
  mocktail: ^0.2.0
  injectable: ^1.5.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.5
  retrofit_generator: '>=4.0.0 <5.0.0'
  json_serializable: '>4.4.0'
  injectable_generator: ^1.5.2
  freezed: ^1.1.0

flutter:

  uses-material-design: true
  assets:
    - assets/
